FROM rabbitmq:3.13-management

ENV RABBITMQ_ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins
ENV RABBITMQ_PLUGINS_DIR=/plugins

# Instala o curl (necessário para baixar o plugin)
RUN apt-get update && apt-get install -y curl

# Baixa o plugin delayed_message_exchange
RUN curl -Lo /plugins/rabbitmq_delayed_message_exchange-3.13.0.ez \
    https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.13.0/rabbitmq_delayed_message_exchange-3.13.0.ez \
 && chmod 644 /plugins/rabbitmq_delayed_message_exchange-3.13.0.ez

# Ativa o plugin
RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange
